version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - psql-data:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql  # push the db_init.sql 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vroomvroom
    networks:
      - vroomvroom-net

  adminer:
    image: adminer
    restart: always
    ports:
      - "1333:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database
    networks:
      - vroomvroom-net

volumes:
  psql-data:

networks:
  vroomvroom-net:
    driver: bridge
